language: python

matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=py27
    - python: 3.6
      env:
        - TOXENV=py36

env:
  matrix:
    - TOXENV=go
    - TOXENV=lua LUA="lua 5.1"
    - TOXENV=lua LUA="lua 5.2"
    - TOXENV=lua LUA="lua 5.3"
    - TOXENV=lua LUA="luajit 2.0"
    - TOXENV=lua LUA="luajit 2.1"

install:
  - pip install tox

script:
  - TRAVIS=true tox

